# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_BDS_rcpp_hello_world', PACKAGE = 'BDS')
}

rcpp_backwards <- function(lambda, mu, eta, u0, bl, nsteps) {
    .Call('_BDS_rcpp_backwards', PACKAGE = 'BDS', lambda, mu, eta, u0, bl, nsteps)
}

rcpp_get_descendants <- function(edge, node_idx) {
    .Call('_BDS_rcpp_get_descendants', PACKAGE = 'BDS', edge, node_idx)
}

rcpp_postorder <- function(lambda, mu, eta, po, edge, branch_lengths, rootnode) {
    .Call('_BDS_rcpp_postorder', PACKAGE = 'BDS', lambda, mu, eta, po, edge, branch_lengths, rootnode)
}

