# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ED_ode <- function(dy, y, lambda, mu, eta, k) {
    invisible(.Call('_Pesto_ED_ode', PACKAGE = 'Pesto', dy, y, lambda, mu, eta, k))
}

EDF_ode <- function(dy, y, lambda, mu, eta, k) {
    invisible(.Call('_Pesto_EDF_ode', PACKAGE = 'Pesto', dy, y, lambda, mu, eta, k))
}

rcpp_backwards <- function(lambda, mu, eta, u0, bl, nsteps) {
    .Call('_Pesto_rcpp_backwards', PACKAGE = 'Pesto', lambda, mu, eta, u0, bl, nsteps)
}

rcpp_forwards <- function(lambda, mu, eta, u0, bl, nsteps) {
    .Call('_Pesto_rcpp_forwards', PACKAGE = 'Pesto', lambda, mu, eta, u0, bl, nsteps)
}

rcpp_get_descendants <- function(edge, node_idx) {
    .Call('_Pesto_rcpp_get_descendants', PACKAGE = 'Pesto', edge, node_idx)
}

rcpp_get_ancestor <- function(edge, node_idx) {
    .Call('_Pesto_rcpp_get_ancestor', PACKAGE = 'Pesto', edge, node_idx)
}

rcpp_postorder <- function(lambda, mu, eta, po, edge, branch_lengths, rootnode, nsteps) {
    .Call('_Pesto_rcpp_postorder', PACKAGE = 'Pesto', lambda, mu, eta, po, edge, branch_lengths, rootnode, nsteps)
}

rcpp_preorder <- function(lambda, mu, eta, po, edge, branch_lengths, root_probs, E_ends, D_ends, D_ends_unnormalized, rootnode, nsteps) {
    .Call('_Pesto_rcpp_preorder', PACKAGE = 'Pesto', lambda, mu, eta, po, edge, branch_lengths, root_probs, E_ends, D_ends, D_ends_unnormalized, rootnode, nsteps)
}

